### ISSUE TITLE
Why is this noisy data generated? 

### ISSUE THREAD

**Issue by jS5t3r** [jayaram-r/adversarial-detection#98]
This script generates noisy data? 
https://github.com/jayaram-r/adversarial-detection/blob/master/expts/generate_noisy_data.py

Why is this done?
For which defenses is that useful?

**Comment by jayaram-r** [comment]
It is used by the 'deep mahalanobis' and 'local intrinsic dimensionality' based defense methods. See this script [detection_main.py](https://github.com/jayaram-r/adversarial-detection/blob/master/expts/detection_main.py) on the following lines: 470 and 611.

**Comment by jayaram-r** [comment]
The script `generate_noisy_data.py` has to be run prior to running the defense methods in order to generate the noisy data.

**Comment by jS5t3r** [comment]
Thanks
